js:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.js'

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'

🖥️web:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.html'

📱styles:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/css/**'

🗄️tests:
  - changed-files:
      - any-glob-to-any-file:
          - 'tests/**'

workflows:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/**'
          - '.github/**/*.yml'