js:
  - changed-files:
      - any-glob-to-any-file:
          - src/js/**

📝documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'

🖥️web:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.html'

📱styles:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/css/**'

🗄️tests:
  - changed-files:
      - any-glob-to-any-file:
          - tests/**