name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: IssueOps Label Manager
  # You may pin to the exact commit or the version.
  # uses: issue-ops/labeler@430e8380347e1b1febbc2777ce5545de5da53d47
      uses: issue-ops/labeler@v2.0.0
      with:
    # The action to take
          action: # optional, default is add
    # Create the label(s) if not present
          create: # optional, default is false
    # The GitHub API token to use
          github_token: # optional, default is ${{ github.token }}
    # A line-separated list of labels to add or remove
          labels: 
    # The issue or PR number
          issue_number: 
    # The repository to use
          repository: # optional, default is ${{ github.repository }}
    - name: IssueOps Releaser
  # You may pin to the exact commit or the version.
  # uses: issue-ops/releaser@8e6ecdd3fd423e3ef82eb8a43cc09581b1bac392
      uses: issue-ops/releaser@v0.1.1
      with:
    # Whether or not the release should be a draft.
        draft: # optional, default is false
    # Whether or not to generate release notes.
        generate_release_notes: # optional, default is true
    # The name of the release. Defaults to the tag name.
        name: # optional
    # The release notes. Will be prepended to the generated release notes if generate_release_notes is enabled.
        notes: # optional
    # The owner of the repository.
        owner: # default is ${{ github.event.repository.owner.login }}
    # Whether or not the release should be a prerelease.
        prerelease: # optional, default is false
    # The repository to create the release in.
        repo: # default is ${{ github.event.repository.name }}
    # The tag to create the release from. If the tag does not exist, it will be created at the branch or commit specified by target_commitish.
        tag: 
    # The branch name or commit SHA to create the release from. This is ignored if the tag already exists in the repository.
        target_commitish: # optional
          